version: '2'

services:
  web-frontend:
    build:
      context: .
      dockerfile: ./docker/web/frontend/Dockerfile
    ports:
      - 80
    depends_on:
      - web-backend


  web-backend:
    build:
      context: .
      dockerfile: ./docker/web/backend/Dockerfile
    volumes:
      - /data/backend-bridge/datadir:/data_backend:rw
    depends_on:
      - db-mysql
  
  db-mysql:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /data/mysql-bridge/datadir:/var/lib/mysql

networks:
  default:
    external:
      name: cplus_net     
